[package]
name = "learngit"
version = "0.1.0"
authors = ["vadim"]
edition = "2018"
repository = "https://github.com/adsick/learngit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
